version: '3'

services:
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '200MB'

  api1:
    build: .
    hostname: api1
    ports:
      - '3000:3000'
    healthcheck:
      test: ['CMD-SHELL', 'curl http://localhost:3000/health']
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '128MB'

  api2:
    build: .
    hostname: api2
    ports:
      - '3001:3000'
    healthcheck:
      test: ['CMD-SHELL', 'curl http://localhost:3000/health']
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '128MB'

  nginx:
    image: nginx:1.24-alpine
    volumes:
      - ./default.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - '9999:9999'
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '94MB'
